<?php
$carreras=array(
array('Diseño Industrial','Facultad de Arquitectura'),
array('Urbanismo','Facultad de Arquitectura'),
array('Artes Visuales','Facultad de Artes y Diseño'),
array('Comunicación Gráfica','Facultad de Artes y Diseño'),
array('Diseño Gráfico','Facultad de Artes y Diseño'),
array('Diseño y Comunicación Visual','Facultad de Artes y Diseño'),
array('Arte y Diseño','Facultad de Artes y Diseño'),
array('Cinematografía','Facultad de Artes y Diseño'),
array('Técnico','Facultad de Artes y Diseño'),
array('Actuaría','Facultad de Ciencias'),
array('Ciencias de la Computación','Facultad de Ciencias'),
array('Física','Facultad de Ciencias'),
array('Matemáticas','Facultad de Ciencias'),
array('Ciencias de la Tierra','Facultad de Ciencias'),
array('Física Biomédica','Facultad de Ciencias'),
array('Matemáticas Aplicadas','Facultad de Ciencias'),
array('Biología','Facultad de Ciencias'),
array('Manejo Sustentable de Zonas Costeras','Facultad de Ciencias'),
array('Técnico','Facultad de Ciencias'),
array('Ciencias de la Comunicación (Periodismo)','Facultad de Ciencias Políticas y Sociales'),
array('Ciencias Políticas y Administración Pública','Facultad de Ciencias Políticas y Sociales'),
array('Relaciones Internacionales','Facultad de Ciencias Políticas y Sociales'),
array('Sociología','Facultad de Ciencias Políticas y Sociales'),
array('Antropología','Facultad de Ciencias Políticas y Sociales'),
array('Ingeniería Química','Facultad de Química'),
array('Ingeniería Química y Metalúrgica','Facultad de Química'),
array('Química','Facultad de Química'),
array('Química de Alimentos','Facultad de Química'),
array('Química Farmacéutico Biológica','Facultad de Química'),
array('Química e Ingeniería en Materiales','Facultad de Química'),
array('Administración','Facultad de Contaduría y Administración'),
array('Contaduría','Facultad de Contaduría y Administración'),
array('Informática','Facultad de Contaduría y Administración'),
array('Negocios Internacionales','Facultad de Contaduría y Administración'),
array('Derecho','Facultad de Derecho'),
array('Economía','Facultad de Economía'),
array('Enfermería y Obstetricia','Facultad de Enfemería'),
array('Enfermería','Facultad de Enfemería'),
array('Técnico','Facultad de Enfemería'),
array('Geografía','Facultad de Filosofía y Letras'),
array('Bibliotecología','Facultad de Filosofía y Letras'),
array('Estudios Latinoamericanos','Facultad de Filosofía y Letras'),
array('Filosofía','Facultad de Filosofía y Letras'),
array('Historia','Facultad de Filosofía y Letras'),
array('Lengua y Literaturas Hispánicas','Facultad de Filosofía y Letras'),
array('Lengua y Literaturas Modernas Alemanas','Facultad de Filosofía y Letras'),
array('Lengua y Literaturas Modernas Francesas','Facultad de Filosofía y Letras'),
array('Lengua y Literaturas Modernas Inglesas','Facultad de Filosofía y Letras'),
array('Lengua y Literaturas Modernas Italianas','Facultad de Filosofía y Letras'),
array('Letras Clásicas','Facultad de Filosofía y Letras'),
array('Literatura Dramática y Teatro','Facultad de Filosofía y Letras'),
array('Pedagogía','Facultad de Filosofía y Letras'),
array('Desarrollo y Gestión Interculturales','Facultad de Filosofía y Letras'),
array('Lengua y Literaturas Modernas Portuguesas','Facultad de Filosofía y Letras'),
array('Administración de Archivos y Gestión Documental','Facultad de Filosofía y Letras'),
array('Técnico','Facultad de Filosofía y Letras'),
array('Ingeniería Civil','Facultad de Ingeniería'),
array('Ingeniería de Minas y Metalurgia','Facultad de Ingeniería'),
array('Ingeniería Eléctrica y Electrónica','Facultad de Ingeniería'),
array('Ingeniería en Computación','Facultad de Ingeniería'),
array('Ingeniería en Telecomunicaciones','Facultad de Ingeniería'),
array('Ingeniería Geofísica','Facultad de Ingeniería'),
array('Ingeniería Geológica','Facultad de Ingeniería'),
array('Ingeniería Industrial','Facultad de Ingeniería'),
array('Ingeniería Mecánica','Facultad de Ingeniería'),
array('Ingeniería Mecánica Eléctrica','Facultad de Ingeniería'),
array('Ingeniería Petrolera','Facultad de Ingeniería'),
array('Ingeniería Topográfica y Geodésica','Facultad de Ingeniería'),
array('Ingeniería Mecatrónica','Facultad de Ingeniería'),
array('Ingeniería Geomática','Facultad de Ingeniería'),
array('Ingeniería en Sistemas Biomédicos','Facultad de Ingeniería'),
array('Ingeniería Ambiental','Facultad de Ingeniería'),
array('Ingeniería Aeroespecial','Facultad de Ingeniería'),
array('Investigación Biomédica Básica','Facultad de Medicina'),
array('Médico Cirujano','Facultad de Medicina'),
array('Fisioterapia','Facultad de Medicina'),
array('Ciencia Forense','Facultad de Medicina'),
array('Neurociencias','Facultad de Medicina'),
array('Ciencia de la Nutrición Humana','Facultad de Medicina'),
array('Canto','Facultad de Música'),
array('Composición','Facultad de Música'),
array('Educación Musical','Facultad de Música'),
array('Etnomusicología','Facultad de Música'),
array('Instrumentista','Facultad de Música'),
array('Piano','Facultad de Música'),
array('Teatro y Actuación','Facultad de Música'),
array('Técnico','Facultad de Música'),
array('Cirujano Dentista','Facultad de Odontología'),
array('Técnico','Facultad de Odontología'),
array('Trabajo Social','Escuela Nacional de Trabajo Social'),
array('Medicina Veterinaria y Zootecnia','Facultad de Medicina Veterinaria y Zootecnia'),
array('Ciencias de la Tierra','Escuela Nacional de Ciencias de la Tierra'),
array('Geografía Aplicada','Escuela Nacional de Ciencias de la Tierra'),
array('Psicología','Facultad de Psicología'),
array('Lingüística Aplicada','Escuela Nacional de Lenguas, Lingüística y Traducción'),
array('Traducción','Escuela Nacional de Lenguas, Lingüística y Traducción'),
array('Cinematografía','Escuela Nacional de Artes Cinematográficas'),
array('Ciencias Genómicas','Centro de Ciencias Genómicas  Instituto de Biotecnología'),
array('Ciencia de Datos','Instituto de Investigaciones en Matemáticas Aplicadas y Sistemas'),
array('Ingeniería en Energías Renovables','Instituto de Energías Renovables'),
array('Nanotecnología','Centro de Nanociencias y Nanotecnología'),
array('Desarrollo y Gestión Interculturales','Centro de Peninsular en Humanidades y Ciencias Sociales'),
array('Tecnología','Centro de Física Aplicada y Tecnología Avanzada'),
array('Ciencias Ambientales','Centro de Investigaciones en Ecosistemas'),
array('Ingeniería Industrial','FES Cuautitlán'),
array('Ingeniería Mecánica Eléctrica','FES Cuautitlán'),
array('Ingeniería Química','FES Cuautitlán'),
array('Tecnología','FES Cuautitlán'),
array('Ingeniería en Telecomunicaciones, Sistemas y Electrónica','FES Cuautitlán'),
array('Ingeniería Agrícola','FES Cuautitlán'),
array('Ingeniería en Alimentos','FES Cuautitlán'),
array('Medicina Veterinaria y Zootecnia','FES Cuautitlán'),
array('Química','FES Cuautitlán'),
array('Química Farmacéutico Biológica','FES Cuautitlán'),
array('Química Industrial','FES Cuautitlán'),
array('Bioquímica Diagnóstica','FES Cuautitlán'),
array('Farmacia','FES Cuautitlán'),
array('Administración','FES Cuautitlán'),
array('Contaduría','FES Cuautitlán'),
array('Informática','FES Cuautitlán'),
array('Diseño y Comunicación Visual','FES Cuautitlán'),
array('Actuaría','FES Acatlán'),
array('Arquitectura','FES Acatlán'),
array('Ingeniería Civil','FES Acatlán'),
array('Matemáticas Aplicadas y Computación','FES Acatlán'),
array('Ciencias de la Comunicación (Periodismo)','FES Acatlán'),
array('Ciencias Políticas y Administración Pública','FES Acatlán'),
array('Derecho','FES Acatlán'),
array('Economía','FES Acatlán'),
array('Relaciones Internacionales','FES Acatlán'),
array('Sociología','FES Acatlán'),
array('Comunicación','FES Acatlán'),
array('Diseño Gráfico','FES Acatlán'),
array('Enseñanza de Inglés','FES Acatlán'),
array('Filosofía','FES Acatlán'),
array('Historia','FES Acatlán'),
array('Lengua y Literaturas Hispánicas','FES Acatlán'),
array('Pedagogía','FES Acatlán'),
array('Enseñanza de Alemán como Lengua Extranjera','FES Acatlán'),
array('Enseñanza de Español como Lengua Extranjera','FES Acatlán'),
array('Enseñanza de Francés como Lengua Extranjera','FES Acatlán'),
array('Enseñanza de Inglés como Lengua Extranjera','FES Acatlán'),
array('Enseñanza de Italiano como Lengua Extranjera','FES Acatlán'),
array('Técnico','FES Acatlán'),
array('Biología','FES Iztacala'),
array('Cirujano Dentista','FES Iztacala'),
array('Enfermería y Obstetricia','FES Iztacala'),
array('Médico Cirujano','FES Iztacala'),
array('Optometría','FES Iztacala'),
array('Psicología','FES Iztacala'),
array('Enfermería','FES Iztacala'),
array('Ecología','FES Iztacala'),
array('Técnico','FES Iztacala'),
array('Arquitectura','FES Aragón'),
array('Diseño Industrial','FES Aragón'),
array('Ingeniería Civil','FES Aragón'),
array('Ingeniería Eléctrica y Electrónica','FES Aragón'),
array('Ingeniería en Computación','FES Aragón'),
array('Ingeniería Industrial','FES Aragón'),
array('Ingeniería Mecánica','FES Aragón'),
array('Ingeniería Mecánica Eléctrica','FES Aragón'),
array('Ciencias de la Comunicación (Periodismo)','FES Aragón'),
array('Derecho','FES Aragón'),
array('Economía','FES Aragón'),
array('Planificación para el Desarrollo Agropecuario','FES Aragón'),
array('Relaciones Internacionales','FES Aragón'),
array('Sociología','FES Aragón'),
array('Comunicación y Periodismo','FES Aragón'),
array('Pedagogía','FES Aragón'),
array('Técnico','FES Aragón'),
array('Ingeniería Química','FES Zaragoza'),
array('Biología','FES Zaragoza'),
array('Cirujano Dentista','FES Zaragoza'),
array('Enfermería y Obstetricia','FES Zaragoza'),
array('Médico Cirujano','FES Zaragoza'),
array('Psicología','FES Zaragoza'),
array('Química Farmacéutico Biológica','FES Zaragoza'),
array('Enfermería','FES Zaragoza'),
array('Nutriología','FES Zaragoza'),
array('Desarrollo Comunitario para el Envejecimiento','FES Zaragoza'),
array('Técnico','FES Zaragoza'),
array('Optometría','ENES León'),
array('Fisioterapia','ENES León'),
array('Odontología','ENES León'),
array('Ciencias Agrogenómicas','ENES León'),
array('Economía Industrial','ENES León'),
array('Administración Agropecuaria','ENES León'),
array('Desarrollo Territorial','ENES León'),
array('Turismo y Desarrollo Sostenible','ENES León'),
array('Desarrollo y Gestión Interculturales','ENES León'),
array('Traducción','ENES León'),
array('Técnico','ENES León'),
array('Geociencias','ENES Morelia'),
array('Tecnologías para la Información en Ciencias','ENES Morelia'),
array('Ciencia de Materiales Sustentables','ENES Morelia'),
array('Ciencias Ambientales','ENES Morelia'),
array('Ecología','ENES Morelia'),
array('Ciencias Agroforestales','ENES Morelia'),
array('Estudios Sociales y Gestión Local','ENES Morelia'),
array('Geohistoria','ENES Morelia'),
array('Literatura Intercultural','ENES Morelia'),
array('Historia del Arte','ENES Morelia'),
array('Arte y Diseño','ENES Morelia'),
array('Administración de Archivos y Gestión Documental','ENES Morelia'),
array('Música y Tecnología Artística','ENES Morelia'),
array('Técnico','ENES Morelia'),
array('Ciencias de la Tierra','ENES Mérida'),
array('Ciencias Ambientales','ENES Mérida'),
array('Manejo Sustentable de Zonas Costeras','ENES Mérida'),
array('Ecología','ENES Mérida'),
array('Geografía Aplicada','ENES Mérida'),
array('Desarrollo y Gestión Interculturales','ENES Mérida'),
array('Técnico','ENES Mérida'),
array('Tecnología','ENES Juriquilla'),
array('Ciencias de la Tierra','ENES Juriquilla'),
array('Ingeniería en Energías Renovables','ENES Juriquilla'),
array('Matemáticas para el Desarrollo','ENES Juriquilla'),
array('Ciencias Genómicas','ENES Juriquilla'),
array('Neurociencias','ENES Juriquilla'),
array('Órtesis y Prótesis','ENES Juriquilla'),
array('Negocios Internacionales','ENES Juriquilla'),
array('Arquitectura','Facultad de Arquitectura'),
array('Arquitectura del paisaje','Facultad de Arquitectura'))
?>
